const types ={
    FIRST_TIME:'FIRST_TIME',
    GET_MODE:'GET_MODE',
    UPDATE_MODE:'UPDATE_MODE',
    UPDATE_MODAL:'UPDATE_MODAL',
    SET_THEME:'SET_THEME',
    GET_THEME:'GET_THEME',
    SET_LANGUAGE:'SET_LANGUAGE',
    GET_LANGUAGE:'GET_LANGUAGE',
    FETCH_SIGNS:'FETCH_SIGNS',
    UPDATE_CONNECTION:'UPDATE_CONNECTION',
}

export default types